### Get Users
GET http://localhost:3000/users


### Get User by Id
GET http://localhost:3000/users/1


### Get user by email
GET http://localhost:3000/users/search?email=titid@gmail.com


### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "silit",
    "email": "silit@gmail.com",
    "password": "12345"
}

### Signin User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "silit@gmail.com",
    "password": "12345"
}


### Signout User
GET http://localhost:3000/auth/signout


### Update user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "lastName": "Perkasa"
}


### Delete user
DELETE http://localhost:3000/auth/3


### Test Session User
GET http://localhost:3000/users/test